In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
telco_cust = pd.read_csv('telco_dataset.csv')
telco_cust.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
telco_cust.columns.values

array(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'Churn'], dtype=object)

In [4]:
# explore if there are missing values
telco_cust.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [5]:
# converting total charges to numerical data types
telco_cust.TotalCharges = pd.to_numeric(
    telco_cust.TotalCharges, errors="coerce")
telco_cust.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
#  remove missing values
telco_cust.dropna(inplace=True)
# remove customerID
telco_cust.drop('customerID', axis=1, inplace=True)
telco_cust

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [7]:
# change male to female
telco_cust['gender'].replace({'Male': 1, 'Female': 0}, inplace=True)

telco_cust.replace("No internet service", "No", inplace=True)
telco_cust.replace("No phone service", "No", inplace=True)

# change (yes, no) to (1,0)
yes_no_columns = ['Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                  'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn']
for col in yes_no_columns:
    telco_cust[col].replace({'Yes': 1, 'No': 0}, inplace=True)

telco_cust

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,0,DSL,1,0,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,DSL,1,0,1,1,1,1,One year,1,Mailed check,84.80,1990.50,0
7039,0,0,1,1,72,1,1,Fiber optic,0,1,1,0,1,1,One year,1,Credit card (automatic),103.20,7362.90,0
7040,0,0,1,1,11,0,0,DSL,1,0,0,0,0,0,Month-to-month,1,Electronic check,29.60,346.45,0
7041,1,1,1,0,4,1,1,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Mailed check,74.40,306.60,1
7042,1,0,0,0,66,1,0,Fiber optic,1,0,1,1,1,1,Two year,1,Bank transfer (automatic),105.65,6844.50,0

In [8]:
# one hot encoding
data = pd.get_dummies(data=telco_cust, columns=[
                      'MultipleLines', 'InternetService', 'Contract', 'PaymentMethod'])

data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,0,0,...,1,0,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,1,0,1,0,...,1,0,0,0,1,0,0,0,0,1
2,1,0,0,0,2,1,1,1,0,0,...,1,0,0,1,0,0,0,0,0,1
3,1,0,0,0,45,0,1,0,1,1,...,1,0,0,0,1,0,1,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,0,1,1,...,1,0,0,0,1,0,0,0,0,1
7039,0,0,1,1,72,1,0,1,1,0,...,0,1,0,0,1,0,0,1,0,0
7040,0,0,1,1,11,0,1,0,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,1,1,1,0,4,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,1,0,0,0,66,1,1,0,1,1,...,0,1,0,0,0,1,1,0,0,0

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# scale all variables to range of 0 to 1
features = data.copy().columns.values
scaler.fit(data)
data = pd.DataFrame(scaler.transform(data))
data.columns = features
data.sample(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
3423,0.0,0.0,1.0,1.0,0.732394,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1374,0.0,0.0,0.0,0.0,0.971831,0.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
5365,0.0,0.0,0.0,0.0,0.126761,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
232,1.0,0.0,0.0,0.0,0.000000,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
667,0.0,0.0,0.0,0.0,0.042254,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [10]:
X = data.drop('Churn', axis=1)
y = data['Churn']

In [11]:
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=25)

In [12]:
num_inputs = len(X_train.columns)
num_inputs

27

In [13]:
import tensorflow as tf
from tensorflow import keras

Init Plugin
Init Graph Optimizer
Init Kernel

In [14]:
model = keras.Sequential([
    keras.layers.Dense(num_inputs, input_shape=(
        num_inputs,), activation="relu"),
    keras.layers.Dense(num_inputs,  activation="relu"),
    keras.layers.Dense(num_inputs, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2021-12-08 15:57:19.441667: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-12-08 15:57:19.441849: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [15]:
model.fit(X_train, y_train, epochs=100)

2021-12-08 15:57:22.535422: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-12-08 15:57:22.535615: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2021-12-08 15:57:22.657214: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.

Epoch 1/100
176/176 [==============================] - 1s 6ms/step - loss: 0.5164 - accuracy: 0.7420
Epoch 2/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4338 - accuracy: 0.7906
Epoch 3/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4243 - accuracy: 0.7993
Epoch 4/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4194 - accuracy: 0.8005
Epoch 5/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4174 - accuracy: 0.8016
Epoch 6/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4162 - accuracy: 0.8009
Epoch 7/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4144 - accuracy: 0.8016
Epoch 8/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4114 - accuracy: 0.8094
Epoch 9/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4095 - accuracy: 0.8107
Epoch 10/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4072 - accuracy: 0.8091
Epoch 11/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4048 - accuracy: 0.8103
Epoch 12/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4025 - accuracy: 0.8119
Epoch 13/100
176/176 [==============================] - 1s 6ms/step - loss: 0.4010 - accuracy: 0.8137
Epoch 14/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3999 - accuracy: 0.8158
Epoch 15/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3981 - accuracy: 0.8140
Epoch 16/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3952 - accuracy: 0.8140
Epoch 17/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3939 - accuracy: 0.8155
Epoch 18/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3918 - accuracy: 0.8148
Epoch 19/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3911 - accuracy: 0.8164
Epoch 20/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3884 - accuracy: 0.8183
Epoch 21/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3892 - accuracy: 0.8144
Epoch 22/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3880 - accuracy: 0.8199
Epoch 23/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3814 - accuracy: 0.8188
Epoch 24/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3831 - accuracy: 0.8204
Epoch 25/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3804 - accuracy: 0.8228
Epoch 26/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3802 - accuracy: 0.8196
Epoch 27/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3790 - accuracy: 0.8228
Epoch 28/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3766 - accuracy: 0.8204
Epoch 29/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3741 - accuracy: 0.8235
Epoch 30/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3741 - accuracy: 0.8231
Epoch 31/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3723 - accuracy: 0.8281
Epoch 32/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3696 - accuracy: 0.8288
Epoch 33/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3672 - accuracy: 0.8272
Epoch 34/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3681 - accuracy: 0.8277
Epoch 35/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3675 - accuracy: 0.8288
Epoch 36/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3632 - accuracy: 0.8311
Epoch 37/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3621 - accuracy: 0.8309
Epoch 38/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3601 - accuracy: 0.8352
Epoch 39/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3585 - accuracy: 0.8320
Epoch 40/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3565 - accuracy: 0.8327
Epoch 41/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3555 - accuracy: 0.8331
Epoch 42/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3550 - accuracy: 0.8324
Epoch 43/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3536 - accuracy: 0.8347
Epoch 44/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3505 - accuracy: 0.8391
Epoch 45/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3486 - accuracy: 0.8373
Epoch 46/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3485 - accuracy: 0.8386
Epoch 47/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3472 - accuracy: 0.8400
Epoch 48/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3456 - accuracy: 0.8388
Epoch 49/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3436 - accuracy: 0.8430
Epoch 50/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3426 - accuracy: 0.8373
Epoch 51/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3399 - accuracy: 0.8428
Epoch 52/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3397 - accuracy: 0.8468
Epoch 53/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3388 - accuracy: 0.8446
Epoch 54/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3376 - accuracy: 0.8444
Epoch 55/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3369 - accuracy: 0.8434
Epoch 56/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3345 - accuracy: 0.8485
Epoch 57/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3335 - accuracy: 0.8453
Epoch 58/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3310 - accuracy: 0.8494
Epoch 59/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3296 - accuracy: 0.8482
Epoch 60/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3293 - accuracy: 0.8487
Epoch 61/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3266 - accuracy: 0.8555
Epoch 62/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3256 - accuracy: 0.8546
Epoch 63/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3230 - accuracy: 0.8533
Epoch 64/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3237 - accuracy: 0.8521
Epoch 65/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3218 - accuracy: 0.8505
Epoch 66/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3218 - accuracy: 0.8580
Epoch 67/100
176/176 [==============================] - 1s 7ms/step - loss: 0.3206 - accuracy: 0.8551
Epoch 68/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3186 - accuracy: 0.8540
Epoch 69/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3183 - accuracy: 0.8564
Epoch 70/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3145 - accuracy: 0.8572
Epoch 71/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3172 - accuracy: 0.8523
Epoch 72/100
176/176 [==============================] - 1s 7ms/step - loss: 0.3139 - accuracy: 0.8572
Epoch 73/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3164 - accuracy: 0.8555
Epoch 74/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3144 - accuracy: 0.8587
Epoch 75/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3093 - accuracy: 0.8599
Epoch 76/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3084 - accuracy: 0.8590
Epoch 77/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3111 - accuracy: 0.8560
Epoch 78/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3086 - accuracy: 0.8576
Epoch 79/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3085 - accuracy: 0.8576
Epoch 80/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3048 - accuracy: 0.8622
Epoch 81/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3049 - accuracy: 0.8652
Epoch 82/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3026 - accuracy: 0.8645
Epoch 83/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3056 - accuracy: 0.8597
Epoch 84/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2983 - accuracy: 0.8661
Epoch 85/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3018 - accuracy: 0.8603
Epoch 86/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2975 - accuracy: 0.8649
Epoch 87/100
176/176 [==============================] - 1s 6ms/step - loss: 0.3004 - accuracy: 0.8613
Epoch 88/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2993 - accuracy: 0.8604
Epoch 89/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2946 - accuracy: 0.8656
Epoch 90/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2950 - accuracy: 0.8665
Epoch 91/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2928 - accuracy: 0.8652
Epoch 92/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2900 - accuracy: 0.8677
Epoch 93/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2883 - accuracy: 0.8672
Epoch 94/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2904 - accuracy: 0.8677
Epoch 95/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2866 - accuracy: 0.8702
Epoch 96/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2876 - accuracy: 0.8709
Epoch 97/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2836 - accuracy: 0.8738
Epoch 98/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2864 - accuracy: 0.8699
Epoch 99/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2832 - accuracy: 0.8734
Epoch 100/100
176/176 [==============================] - 1s 6ms/step - loss: 0.2824 - accuracy: 0.8708

In [19]:
model.evaluate(x_test, y_test)

44/44 [==============================] - 0s 4ms/step - loss: 0.5759 - accuracy: 0.7584

[0.5759423971176147, 0.7583511471748352]

In [23]:
y_predict = model.predict(x_test)
y_predict > 0.5

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict > 0.5))

              precision    recall  f1-score   support

         0.0       0.83      0.85      0.84      1053
         1.0       0.52      0.48      0.50       354

    accuracy                           0.76      1407
   macro avg       0.68      0.67      0.67      1407
weighted avg       0.75      0.76      0.75      1407